<?php
/*
 * FastLayer advanced-cache.php drop-in.
 *
 * Ownership marker: wp-fastlayer:advanced-cache-dropin
 *
 * This file is installed and managed automatically by FastLayer. The marker
 * above is how FastLayer tells its own drop-in apart from a drop-in owned by
 * another caching plugin, so that it never overwrites or deletes foreign
 * files. Do not remove the marker, and do not edit this file by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$cache_dir = WP_CONTENT_DIR . '/cache/wp-fastlayer/';
$config_file = $cache_dir . 'config.php';
$options = array();
if ( file_exists( $config_file ) ) {
    $options = include $config_file;
}

$cache_expiration = 36000;
if ( isset( $options['cache_expiration'] ) ) {
    $cache_expiration = max( 1, (int) $options['cache_expiration'] ) * 3600;
}

function wp_fastlayer_cache_enabled() {
    global $options;
    return isset( $options['enable_cache'] ) && '1' === $options['enable_cache'];
}

function wp_fastlayer_get_option_lines( $key ) {
    global $options;
    if ( ! isset( $options[ $key ] ) || ! is_string( $options[ $key ] ) ) {
        return array();
    }
    return preg_split( '/\r?\n/', trim( $options[ $key ] ) );
}

function wp_fastlayer_host_from_url( $url ) {
    if ( ! is_string( $url ) || '' === $url ) {
        return '';
    }
    $parts = parse_url( $url );
    if ( ! is_array( $parts ) || empty( $parts['host'] ) ) {
        return '';
    }
    return strtolower( $parts['host'] );
}

function wp_fastlayer_expected_hosts() {
    global $options;
    $hosts = array();

    if ( isset( $options['_home_host'] ) && is_array( $options['_home_host'] ) ) {
        foreach ( $options['_home_host'] as $host ) {
            if ( is_string( $host ) && '' !== $host ) {
                $hosts[] = strtolower( $host );
            }
        }
    }

    foreach ( array( 'WP_HOME', 'WP_SITEURL' ) as $constant_name ) {
        if ( defined( $constant_name ) ) {
            $host = wp_fastlayer_host_from_url( constant( $constant_name ) );
            if ( '' !== $host ) {
                $hosts[] = $host;
            }
        }
    }

    return array_values( array_unique( $hosts ) );
}

function wp_fastlayer_normalize_request_host() {
    if ( ! isset( $_SERVER['HTTP_HOST'] ) || ! is_string( $_SERVER['HTTP_HOST'] ) ) {
        return '';
    }

    $host = strtolower( trim( $_SERVER['HTTP_HOST'] ) );
    $colon = strpos( $host, ':' );
    if ( false !== $colon ) {
        $host = substr( $host, 0, $colon );
    }

    if ( ! preg_match( '/^[a-z0-9]([a-z0-9._-]*[a-z0-9])?$/', $host ) ) {
        return '';
    }

    return $host;
}

function wp_fastlayer_is_request_host_trusted() {
    $expected = wp_fastlayer_expected_hosts();
    if ( empty( $expected ) ) {
        return false;
    }

    $host = wp_fastlayer_normalize_request_host();
    if ( '' === $host ) {
        return false;
    }

    return in_array( $host, $expected, true );
}

function wp_fastlayer_strip_url_domain( $url ) {
    // WordPress is not loaded this early, so this mirrors the runtime
    // Page_Cache::strip_url_domain() using the native parse_url() instead of
    // wp_parse_url(). Both cache paths must agree on what an exclusion matches.
    $parsed = parse_url( $url );
    if ( ! is_array( $parsed ) || empty( $parsed['path'] ) ) {
        return $url;
    }

    $path = $parsed['path'];
    if ( isset( $parsed['query'] ) ) {
        $path .= '?' . $parsed['query'];
    }

    return $path;
}

function wp_fastlayer_matches_patterns( $value, $patterns ) {
    foreach ( $patterns as $pattern ) {
        $pattern = trim( $pattern );
        if ( '' === $pattern ) {
            continue;
        }

        if ( false !== strpos( $pattern, '*' ) || false !== strpos( $pattern, '(.*)' ) ) {
            $regex = '#^' . str_replace( array( '\*', '(.*)' ), array( '.*', '.*' ), preg_quote( $pattern, '#' ) ) . '$#i';
            if ( preg_match( $regex, $value ) || preg_match( $regex, wp_fastlayer_strip_url_domain( $value ) ) ) {
                return true;
            }
            continue;
        }

        $value_compare   = wp_fastlayer_strip_url_domain( $value );
        $pattern_compare = wp_fastlayer_strip_url_domain( $pattern );

        if ( stripos( $value_compare, $pattern_compare ) !== false || stripos( $value, $pattern ) !== false ) {
            return true;
        }
    }

    return false;
}

function wp_fastlayer_has_excluded_cookie() {
    $patterns = wp_fastlayer_get_option_lines( 'exclude_cookies' );
    if ( empty( $patterns ) || ! isset( $_COOKIE ) || ! is_array( $_COOKIE ) ) {
        return false;
    }

    foreach ( $patterns as $pattern ) {
        $pattern = trim( $pattern );
        if ( '' === $pattern ) {
            continue;
        }
        foreach ( $_COOKIE as $cookie_name => $cookie_value ) {
            if ( stripos( (string) $cookie_name, $pattern ) !== false ) {
                return true;
            }
        }
    }

    return false;
}

function wp_fastlayer_should_skip_cache() {
    // WordPress is not loaded this early, so HTTP_HOST is fully client
    // controlled. It must be validated before it can be used in a cache key.
    if ( ! wp_fastlayer_is_request_host_trusted() ) {
        return true;
    }

    // FastLayer's preload job reads the sitemap documents over HTTP in order to
    // discover which pages to warm. Those responses are XML, not HTML, so they
    // must never become a cache entry that a later request could be served.
    // Only FastLayer's own preload requests carry this header, so visitors are
    // unaffected.
    if ( ! empty( $_SERVER['HTTP_X_FASTLAYER_PRELOAD'] ) ) {
        return true;
    }

    // Check logged in cookie first, since is_user_logged_in() is not defined early.
    if ( isset( $_COOKIE ) && is_array( $_COOKIE ) ) {
        foreach ( $_COOKIE as $key => $value ) {
            if ( 0 === strpos( $key, 'wordpress_logged_in_' ) ) {
                return true;
            }
        }
    }

    if ( function_exists( 'is_user_logged_in' ) && is_user_logged_in() ) {
        return true;
    }

    // POST and HEAD are both excluded, matching class-page-cache.php.
    if ( isset( $_SERVER['REQUEST_METHOD'] ) && is_string( $_SERVER['REQUEST_METHOD'] ) ) {
        if ( in_array( strtoupper( $_SERVER['REQUEST_METHOD'] ), array( 'POST', 'HEAD' ), true ) ) {
            return true;
        }
    }

    if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
        return true;
    }

    if ( defined( 'DOING_CRON' ) && DOING_CRON ) {
        return true;
    }

    if ( defined( 'XMLRPC_REQUEST' ) && XMLRPC_REQUEST ) {
        return true;
    }

    if ( defined( 'WP_ADMIN' ) && WP_ADMIN ) {
        return true;
    }

    $request_uri = isset( $_SERVER['REQUEST_URI'] ) && is_string( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '';

    // REST_REQUEST is defined long after this drop-in runs, so match both the
    // pretty permalink path and the ?rest_route= query form as well.
    if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
        return true;
    }
    if ( false !== strpos( $request_uri, 'rest_route=' ) ) {
        return true;
    }

    // Preview and search, matching is_preview() and is_search() at runtime.
    if ( isset( $_GET['preview'] ) || isset( $_GET['preview_id'] ) || isset( $_GET['post_preview'] ) ) {
        return true;
    }
    if ( isset( $_GET['s'] ) ) {
        return true;
    }
    // A 404 cannot be detected before WordPress parses the query. It is already
    // covered the other way round: class-page-cache.php never writes a 404 or
    // search response to disk, so no such file exists for this drop-in to serve.

    $skip_paths = array(
        '/wp-admin/',
        '/wp-login.php',
        '/wp-register.php',
        '/wp-json/',
        '/cart/',
        '/checkout/',
        '/my-account/',
        '/feed/',
    );

    foreach ( $skip_paths as $path ) {
        if ( false !== strpos( $request_uri, $path ) ) {
            return true;
        }
    }

    if ( wp_fastlayer_matches_patterns( $request_uri, wp_fastlayer_get_option_lines( 'exclude_urls' ) ) ) {
        return true;
    }

    if ( wp_fastlayer_has_excluded_cookie() ) {
        return true;
    }

    $user_agent = isset( $_SERVER['HTTP_USER_AGENT'] ) && is_string( $_SERVER['HTTP_USER_AGENT'] ) ? $_SERVER['HTTP_USER_AGENT'] : '';
    if ( wp_fastlayer_matches_patterns( $user_agent, wp_fastlayer_get_option_lines( 'exclude_user_agents' ) ) ) {
        return true;
    }

    return false;
}

function wp_fastlayer_get_accept_cache_variant() {
    $accept = isset( $_SERVER['HTTP_ACCEPT'] ) && is_string( $_SERVER['HTTP_ACCEPT'] ) ? strtolower( $_SERVER['HTTP_ACCEPT'] ) : '';

    if ( false !== strpos( $accept, 'image/avif' ) ) {
        return 'accept-avif';
    }

    if ( false !== strpos( $accept, 'image/webp' ) ) {
        return 'accept-webp';
    }

    return 'accept-legacy';
}

function wp_fastlayer_get_cache_file() {
    global $cache_dir;

    $protocol = function_exists( 'is_ssl' ) && is_ssl() ? 'https' : 'http';
    $host = isset( $_SERVER['HTTP_HOST'] ) && is_string( $_SERVER['HTTP_HOST'] ) ? $_SERVER['HTTP_HOST'] : '';
    $request_uri = isset( $_SERVER['REQUEST_URI'] ) && is_string( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '';
    $url = $protocol . '://' . $host . $request_uri;
    $cache_key = md5( $url . '|' . wp_fastlayer_get_accept_cache_variant() );

    return $cache_dir . $cache_key . '.html';
}

function wp_fastlayer_is_cache_expired( $file ) {
    global $cache_expiration;
    return ( time() - filemtime( $file ) ) > $cache_expiration;
}

function wp_fastlayer_is_safe_path( $path ) {
    global $cache_dir;
    $realpath = realpath( $path );
    if ( false === $realpath ) {
        return false;
    }

    $cache_realpath = realpath( $cache_dir );
    if ( false === $cache_realpath ) {
        return false;
    }

    return 0 === strpos( $realpath, $cache_realpath );
}

if ( wp_fastlayer_cache_enabled() && ! wp_fastlayer_should_skip_cache() ) {
    $cache_file = wp_fastlayer_get_cache_file();

    if ( file_exists( $cache_file ) && wp_fastlayer_is_safe_path( $cache_file ) ) {
        if ( wp_fastlayer_is_cache_expired( $cache_file ) ) {
            @unlink( $cache_file );
        } else {
            if ( ! headers_sent() ) {
                $expiration = $cache_expiration;
                header( 'Vary: Accept', false );
                header( 'X-Cache-Status: HIT' );
                header( 'Cache-Control: public, max-age=' . $expiration . ', s-maxage=' . $expiration );
                header( 'X-Cache-Generated: yes' );
            }
            readfile( $cache_file );
            exit;
        }
    }
}
